//! Encrypted expanded-plaintext BFV inner product, before digit removal.
//!
//! The evaluator receives public `a0,a1` and an encryption of the work secret.
//! It emits a main-basis Montgomery ciphertext of `a0 + a1*s mod P`. It never
//! receives a secret key and never reconstructs a ciphertext coefficient.
//! This stage does not remove the low digits or refresh the work ciphertext.

use crate::arithmetic::main_only_base_ext::MainOnlyBaseExt;
use crate::arithmetic::rns::U512;
use crate::arithmetic::RNSPolynomial;
use crate::errors::{Nine65Error, Nine65Result};
use crate::keys::bootstrap::{
    screen_bootstrap_security, validate_bootstrap_primes, BootstrapSecurityScreen,
};
use crate::keys::expanded_bootstrap::ExpandedBootstrapKey;
use crate::ops::expanded_phase1::ExpandedPhase1Components;
use crate::ops::rns_fhe::{RNSCiphertext, RNSFHEContext};

fn bits(x: U512) -> u32 {
    for (offset, limb) in [(384, x.d3), (256, x.d2), (128, x.d1), (0, x.d0)] {
        if limb != 0 {
            return offset + 128 - limb.leading_zeros();
        }
    }
    0
}

fn ge(a: U512, b: U512) -> bool {
    (a.d3, a.d2, a.d1, a.d0) >= (b.d3, b.d2, b.d1, b.d0)
}

/// Worst-case, coefficient-wise bounds for this stage, derived from public
/// parameters. They assume keys generated by `ExpandedBootstrapKey` with
/// ternary secrets and CBD errors of magnitude at most `eta`.
#[derive(Debug, Clone)]
pub struct ExpandedInnerProductCertificate {
    pub plaintext_modulus: u64,
    pub ring_degree: usize,
    pub zero_encryption_error_bound: U512,
    pub phase_error_bound: U512,
    pub half_delta: U512,
    pub encoding_remainder: u64,
    /// In-tree screening evidence, not an independent security attestation.
    pub security_screen: BootstrapSecurityScreen,
}

pub struct ExpandedPhaseEvaluator<'a> {
    pub(crate) ctx: &'a RNSFHEContext,
    pub(crate) base_plaintext: u64,
    pub(crate) exponent: u32,
    certificate: ExpandedInnerProductCertificate,
}

impl<'a> ExpandedPhaseEvaluator<'a> {
    pub fn new(ctx: &'a RNSFHEContext, base_plaintext: u64, exponent: u32) -> Nine65Result<Self> {
        let expanded =
            base_plaintext
                .checked_pow(exponent)
                .ok_or_else(|| Nine65Error::BootstrapOverflow {
                    operation: "expanded plaintext power".into(),
                })?;
        if base_plaintext < 3
            || base_plaintext % 2 == 0
            || exponent < 2
            || expanded > i64::MAX as u64
            || ctx.t != expanded
            || ctx.config.t != expanded
            || ctx.n != ctx.config.n
            || ctx.n < 2
            || !ctx.n.is_power_of_two()
        {
            return Err(Nine65Error::BootstrapConfigMismatch {
                reason: "expanded evaluator needs matching odd plaintext t^e, e>=2, and a power-of-two ring".into(),
            });
        }
        validate_bootstrap_primes(&ctx.config.primes, ctx.n)?;
        // Key generation's full-width sampler and this route's future rank
        // operations must not receive a chain that silently wraps U256.
        MainOnlyBaseExt::new(&ctx.config.primes, &[expanded]).map_err(|error| {
            Nine65Error::BootstrapConfigMismatch {
                reason: format!("expanded main-basis capacity: {error:?}"),
            }
        })?;
        let q = U512::product_u64s(&ctx.config.primes);
        let delta = q.div_u64(expanded);
        if ctx.delta_rns.len() != ctx.config.primes.len()
            || ctx.ntt_engines.len() != ctx.config.primes.len()
            || ctx.rns.mont_contexts.len() != ctx.config.primes.len()
            || ctx.rns.primes != ctx.config.primes
            || ctx
                .delta_rns
                .iter()
                .zip(&ctx.config.primes)
                .any(|(&residue, &prime)| residue != delta.mod_u64(prime))
        {
            return Err(Nine65Error::BootstrapConfigMismatch {
                reason: "expanded context has inconsistent basis or encoding scale".into(),
            });
        }
        let n = ctx.n as u128;
        // Enc(0) error = -e_pk*u + e0 + e1*s_boot. All secrets and u are
        // ternary, every CBD error is bounded by eta, and each convolution
        // coefficient has N terms. Thus beta = eta*(2N+1).
        let beta = U512::from_u128(2 * n + 1).mul_u128(ctx.config.eta as u128);
        let multiplier_l1 = n * ((expanded - 1) / 2) as u128;
        let remainder = q.mod_u64(expanded);
        // Centered inputs have |a0+a1*s| <= (N+1)*(P-1)/2. Reducing the
        // phase to its centered mod-P value introduces at most N+1 multiples
        // of P; Delta*P = Q-r therefore contributes at most (N+1)*r noise.
        // The exact Q/P decoding grid adds at most r/2 beyond floored Delta.
        let error_bound = beta
            .mul_u128(multiplier_l1)
            .add(U512::from_u64(remainder).mul_u128(n + 1))
            .add(U512::from_u64(remainder / 2 + remainder % 2));
        let half_delta = delta.div_u64(2);
        if ge(error_bound, half_delta) {
            return Err(Nine65Error::BootstrapFailed {
                reason: format!("expanded inner product lacks worst-case headroom: error bound {} bits, half-Delta {} bits", bits(error_bound), bits(half_delta)),
            });
        }
        let target = (ctx.config.security_bits as u32).max(128);
        let security_screen = screen_bootstrap_security(&ctx.config.primes, ctx.n, target)?;
        if !security_screen.meets_claim_under_both {
            return Err(Nine65Error::SecurityLevelNotMet {
                bits: security_screen.binding_bits,
                required: target,
            });
        }
        Ok(Self {
            ctx,
            base_plaintext,
            exponent,
            certificate: ExpandedInnerProductCertificate {
                plaintext_modulus: expanded,
                ring_degree: ctx.n,
                zero_encryption_error_bound: beta,
                phase_error_bound: error_bound,
                half_delta,
                encoding_remainder: remainder,
                security_screen,
            },
        })
    }

    pub fn certificate(&self) -> &ExpandedInnerProductCertificate {
        &self.certificate
    }

    /// Encrypt the expanded phase using only the public component polynomials
    /// and bootstrap key. The result uses the persistent Montgomery domain of
    /// `RNSCiphertext`, and contains no anchor/auxiliary lanes.
    pub fn inner_product(
        &self,
        components: &ExpandedPhase1Components,
        key: &ExpandedBootstrapKey,
    ) -> Nine65Result<RNSCiphertext> {
        let ctx = self.ctx;
        let p = self.certificate.plaintext_modulus;
        if key.primes != ctx.config.primes
            || key.n != ctx.n
            || key.plaintext_modulus != p
            || key.base_plaintext != self.base_plaintext
            || key.exponent != self.exponent
            || key.eta != ctx.config.eta
            || components.plaintext_modulus != p
            || components.digit_divisor != p / self.base_plaintext
            || components.source_level == 0
            || components.source_level > key.work_levels
        {
            return Err(Nine65Error::BootstrapConfigMismatch {
                reason: "expanded component/key/context regime mismatch".into(),
            });
        }
        for values in [&components.c0, &components.c1] {
            if values.len() != ctx.n {
                return Err(Nine65Error::InvalidPolynomialDegree {
                    got: values.len(),
                    expected: ctx.n,
                });
            }
            if values.iter().any(|&value| value >= p) {
                return Err(Nine65Error::InvalidParameter {
                    message: "expanded component is not canonical modulo P".into(),
                });
            }
        }
        let mut c0 = Vec::with_capacity(ctx.config.primes.len());
        let mut c1 = Vec::with_capacity(ctx.config.primes.len());
        for (lane, &q_i) in ctx.config.primes.iter().enumerate() {
            let centered_residue = |value: u64| -> u64 {
                if value <= p / 2 {
                    value % q_i
                } else {
                    let magnitude = (p - value) % q_i;
                    if magnitude == 0 {
                        0
                    } else {
                        q_i - magnitude
                    }
                }
            };
            let a1: Vec<u64> = components.c1.iter().map(|&v| centered_residue(v)).collect();
            let mont = &ctx.rns.mont_contexts[lane];
            let key0: Vec<u64> = key.enc_s.c0.limbs[lane]
                .iter()
                .map(|&v| mont.from_montgomery(v))
                .collect();
            let key1: Vec<u64> = key.enc_s.c1.limbs[lane]
                .iter()
                .map(|&v| mont.from_montgomery(v))
                .collect();
            let mut product0 = ctx.ntt_engines[lane].multiply(&a1, &key0);
            let product1 = ctx.ntt_engines[lane].multiply(&a1, &key1);
            for (value, &a0) in product0.iter_mut().zip(&components.c0) {
                let message =
                    (centered_residue(a0) as u128 * ctx.delta_rns[lane] as u128) % q_i as u128;
                *value = mont.to_montgomery(((*value as u128 + message) % q_i as u128) as u64);
            }
            c0.push(product0);
            c1.push(product1.iter().map(|&v| mont.to_montgomery(v)).collect());
        }
        Ok(RNSCiphertext {
            c0: RNSPolynomial {
                limbs: c0,
                n: ctx.n,
            },
            c1: RNSPolynomial {
                limbs: c1,
                n: ctx.n,
            },
            num_primes: ctx.config.primes.len(),
        })
    }
}
