//! Independent verification of [`crate::arithmetic::compare_bit`] against an
//! EXTERNAL oracle, on the real shipped prime chains.
//!
//! The kernel ships with its own exhaustive tests. Those establish internal
//! consistency; this module establishes something the kernel cannot establish
//! about itself:
//!
//! 1. **External ground truth.** `compare_bit_vectors.rs` was generated by an
//!    arbitrary-precision Python run OUTSIDE this crate — residues and the
//!    true bit `[2X >= M]` both computed there. A shared bug between the
//!    kernel and a Rust-side oracle cannot hide here, because the oracle is
//!    not Rust and does not share a line of code with the kernel.
//! 2. **The real chains.** The kernel's own tests use small/synthetic bases
//!    (3·5·7·11·13, 42-bit triples). These vectors use the exact
//!    `secure_128` / `secure_192` / `secure_256` main chains from
//!    `params::secure_configs` — 119, 146 and 175 bits, i.e. two of the three
//!    exceed `u128` and exercise the U256 fallback arithmetic for real.
//! 3. **Boundary adversariality.** Every vector set hugs all three dangerous
//!    regions (`X ~ 0`, `X ~ M/2`, `X ~ M`) at distance 0..39, which is inside
//!    the fast path's ambiguous bands, so the exact fallback is forced rather
//!    than merely available.

#[cfg(test)]
mod tests {
    use super::super::compare_bit::{CompareBit, ComparePath};
    use super::super::compare_bit_vectors::ORACLE_VECTORS;

    /// The load-bearing test: kernel vs external arbitrary-precision oracle on
    /// the shipped chains. A disagreement here is a real defect, not a
    /// disagreement between two of our own implementations.
    #[test]
    fn matches_external_oracle_on_the_real_shipped_chains() {
        let mut checked = 0u64;
        let mut fallbacks = 0u64;
        for (name, primes, vectors) in ORACLE_VECTORS {
            let kb = CompareBit::new(primes);
            for (residues, expected) in vectors.iter() {
                let (got, path) = kb.decide_with_path(residues);
                assert_eq!(
                    got, *expected,
                    "{name}: wrong comparison bit for residues {residues:?}"
                );
                checked += 1;
                fallbacks += (*path_is_fallback(&path)) as u64;
            }
        }
        assert_eq!(
            checked, 1680,
            "vector set shrank — regenerate or investigate"
        );
        // Never-vacuous: the boundary vectors MUST drive the exact fallback.
        // If this fires as 0 the fast path is silently deciding cases the
        // theorem says it must refuse, which is the dangerous failure mode.
        assert!(
            fallbacks > 0,
            "exact fallback never fired across {checked} boundary-adversarial \
             vectors — the margin bands are not where the theorem places them"
        );
        println!(
            "compare_bit vs external oracle: {checked}/{checked} exact, \
             {fallbacks} decided by the exact fallback"
        );
    }

    fn path_is_fallback(p: &ComparePath) -> &bool {
        match p {
            ComparePath::ExactFallback => &true,
            ComparePath::Fast => &false,
        }
    }

    /// Speed against the path this kernel would replace: the comparison bit as
    /// `mod_switch_down_dual` obtains it today — full `crt_reconstruct_u256`
    /// followed by the `SignedU256::center` half-modulus comparison.
    ///
    /// `#[ignore]` — run explicitly:
    /// `cargo test -p nine65 --lib --release --features allow_insecure
    ///  compare_bit_speed -- --ignored --nocapture`
    #[test]
    #[ignore]
    fn compare_bit_speed_vs_the_shipped_reconstruction() {
        use crate::arithmetic::integer_math::format_ratio;
        use crate::arithmetic::rns::crt_reconstruct_u256;
        use crate::arithmetic::U256;
        use std::time::Instant;

        for (name, primes, vectors) in ORACLE_VECTORS {
            let kb = CompareBit::new(primes);
            let m = U256::product_u64s(primes);
            let half = m.shr1();
            let cases: Vec<&[u64]> = vectors.iter().map(|(r, _)| *r).collect();
            let reps = 200usize;

            // Shipped path: reconstruct, then compare against M/2.
            let t0 = Instant::now();
            let mut sink = 0u64;
            for _ in 0..reps {
                for r in &cases {
                    let v = crt_reconstruct_u256(r, primes);
                    sink ^= v.gt(half) as u64;
                }
            }
            let shipped_total_ns = t0.elapsed().as_nanos();

            // FAIR baseline: the same reconstruction with basis-derived
            // constants hoisted. `crt_reconstruct_u256` recomputes
            // `U512::product_u64s`, `div_u64` and `mod_inverse` on EVERY call
            // — the same uncached-constant disease fixed in `unified_rescale`
            // this cycle. Comparing only against it would credit the kernel
            // for a defect in the baseline rather than for its algorithm, so
            // precompute the per-lane weights `w_i = (M/m_i)·(M/m_i)^-1` once
            // and reduce the sum `S < k·M` by subtraction, exactly as the
            // kernel's own exact fallback does.
            let weights: Vec<U256> = primes
                .iter()
                .map(|&p| {
                    let mi = m.div_mod_u64(p).0;
                    let inv = crate::arithmetic::rns::mod_inverse(mi.mod_u64(p), p);
                    mi.mul_u64(inv)
                })
                .collect();
            let t2 = Instant::now();
            let mut sink3 = 0u64;
            for _ in 0..reps {
                for r in &cases {
                    let mut s = U256::zero();
                    for (i, &p) in primes.iter().enumerate() {
                        s = s.add(weights[i].mul_u64(r[i] % p));
                    }
                    while s.ge(m) {
                        s = s.sub(m);
                    }
                    sink3 ^= s.gt(half) as u64;
                }
            }
            let hoisted_total_ns = t2.elapsed().as_nanos();

            // Kernel.
            let t1 = Instant::now();
            let mut sink2 = 0u64;
            for _ in 0..reps {
                for r in &cases {
                    sink2 ^= kb.decide(r) as u64;
                }
            }
            let kernel_total_ns = t1.elapsed().as_nanos();
            std::hint::black_box((sink, sink2, sink3));

            let total_ops = (reps * cases.len()) as u128;
            // Per-op nanoseconds for display. The two "vs" ratios below are
            // computed directly from the TOTAL nanoseconds, not from these
            // already-divided per-op figures: `total_ops` cancels exactly out
            // of `(shipped_total_ns/total_ops) / (kernel_total_ns/total_ops)`,
            // so cross-cancelling first avoids two rounding steps for one.
            let shipped_ns = format_ratio(shipped_total_ns, total_ops, 1);
            let hoisted_ns = format_ratio(hoisted_total_ns, total_ops, 1);
            let kernel_ns = format_ratio(kernel_total_ns, total_ops, 1);
            // `.max(1)` mirrors the original `.max(0.001)` floor on the
            // per-op kernel time: guard against a division by an
            // (implausible) zero-nanosecond kernel total.
            let vs_shipped = format_ratio(shipped_total_ns, kernel_total_ns.max(1), 1);
            let vs_hoisted = format_ratio(hoisted_total_ns, kernel_total_ns.max(1), 2);

            println!(
                "{name:<11} shipped {shipped_ns:>8} ns | hoisted-recon {hoisted_ns:>7} ns | \
                 compare_bit {kernel_ns:>6} ns || vs shipped {vs_shipped:>6}x | vs hoisted {vs_hoisted:>5}x"
            );
        }
    }
}
