"""Type stubs for the compiled `nine65_python._nine65_python` extension.

Kept by hand alongside `src/lib.rs` -- there is no `#[pyclass]`/`#[pymethods]`
stub generator wired into this build, so if you add or rename a method over
there, update this file too (`python/nine65_python/__init__.py` re-exports
everything declared here).
"""

from __future__ import annotations

class FHEConfig:
    @staticmethod
    def standard_128() -> "FHEConfig": ...
    @staticmethod
    def high_192() -> "FHEConfig": ...
    @staticmethod
    def large_single() -> "FHEConfig": ...
    def name(self) -> str: ...
    def degree(self) -> int: ...
    def plaintext_modulus(self) -> int: ...
    def ciphertext_modulus(self) -> int: ...
    def security_bits(self) -> int: ...
    def eta(self) -> int: ...

class SecureConfig:
    @staticmethod
    def secure_128() -> "SecureConfig": ...
    @staticmethod
    def secure_192() -> "SecureConfig": ...
    @staticmethod
    def secure_256() -> "SecureConfig": ...
    def is_production_safe(self) -> bool: ...
    def classical_security(self) -> int: ...
    def hybrid_security(self) -> int: ...
    def quantum_security(self) -> int: ...
    def he_standard_compliant(self) -> bool: ...
    def to_config(self) -> FHEConfig: ...

class PublicKey:
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> "PublicKey": ...

class SecretKey: ...

class EvaluationKey:
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> "EvaluationKey": ...

class Ciphertext:
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> "Ciphertext": ...

class KeySet:
    @property
    def public_key(self) -> PublicKey: ...
    @property
    def secret_key(self) -> SecretKey: ...
    @property
    def evaluation_key(self) -> EvaluationKey: ...

class FHEContext:
    def __init__(self, config: FHEConfig) -> None: ...
    @staticmethod
    def from_secure_config(config: SecureConfig) -> "FHEContext": ...
    def config(self) -> FHEConfig: ...
    def name(self) -> str: ...
    def degree(self) -> int: ...
    def plaintext_modulus(self) -> int: ...
    def ciphertext_modulus(self) -> int: ...
    def generate_keyset_secure(self) -> KeySet: ...
    def generate_keyset_seeded(self, seed: int) -> KeySet: ...
    def encrypt(self, value: int, public_key: PublicKey) -> Ciphertext: ...
    def encrypt_seeded(self, value: int, public_key: PublicKey, seed: int) -> Ciphertext: ...
    def decrypt(self, ciphertext: Ciphertext, secret_key: SecretKey) -> int: ...
    def add(self, ct1: Ciphertext, ct2: Ciphertext) -> Ciphertext: ...
    def add_plain(self, ciphertext: Ciphertext, value: int) -> Ciphertext: ...
    def mul_plain(self, ciphertext: Ciphertext, value: int) -> Ciphertext: ...
    def mul(
        self, ct1: Ciphertext, ct2: Ciphertext, eval_key: EvaluationKey
    ) -> Ciphertext: ...
    def mul_capacity(self) -> tuple[bool, int]: ...
    def boundary_report(self) -> tuple[int, str, str]: ...
    def batch_encrypt(
        self, values: list[int], public_key: PublicKey
    ) -> list[Ciphertext]: ...
    def batch_decrypt(
        self, ciphertexts: list[Ciphertext], secret_key: SecretKey
    ) -> list[int]: ...
